---
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:8080'
    environment:
      - POSTGRES_USER=scalaexercises_dev_user
      - POSTGRES_PASSWORD=scalaexercises_pass
      - POSTGRES_DB=scalaexercises_dev
