#!/bin/sh

docker-compose -f ./docker-compose.yml stop postgres
docker-compose -f ./docker-compose.yml rm -f postgres
docker-compose -f ./docker-compose.yml up -d postgres

echo -e "Docker ps"
docker ps
